name: Deploy Frontend to Github Pages

on:
  push:
    tags:
      - v*
  workflow_dispatch:

env:
  # Change this if the backend host ever changes
  PUBLIC_BACKEND_HOST: https://pokelink-backend.vercel.app

  # Used in svelte.config.js
  BASE_PATH: '/${{ github.event.repository.name }}'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies and build
        run: | 
          cd frontend
          npm install
          npm run build

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: frontend/build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
