name: Deploy Backend to Vercel

on:
  push:
    tags:
      - v*
  workflow_dispatch:

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install and use the vercel cli
        run: |
          cd backend

          # Install Vercel CLI
          npm install --global vercel@latest

          # Pull Vercel Environment Information
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

          # Deploy Project artifacts to Vercel
          vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
